/**
 * AUTO-GENERATED by scripts/sync-codeforces.mjs — do not edit by hand.
 * Source: public Codeforces API (user.info, user.rating, user.status).
 * Generated: 2026-10-02
 */

export interface CfContest {
  date: string;
  name: string;
  rank: number;
  from: number;
  to: number;
}

export const cfHandle = "bvarshith_77";
export const cfProfileUrl = "https://codeforces.com/profile/bvarshith_77";

export const cfRating = 1641;
export const cfMaxRating = 1641;
export const cfRank = "expert";
export const cfMaxRank = "expert";
export const cfRegistered = "2024-05-26";

export const cfStats = {
  contests: 22,
  problemsSolved: 470,
  submissions: 1065,
  accepted: 474,
  bestRank: 495,
  languages: {
  "C++23 (GCC 14-64, msys2)": 289,
  "C++17 (GCC 7-32)": 766,
  "Python 3": 1,
  "Java 21": 9
},
  verdicts: {
  "OK": 474,
  "WRONG_ANSWER": 425,
  "TIME_LIMIT_EXCEEDED": 126,
  "COMPILATION_ERROR": 7,
  "MEMORY_LIMIT_EXCEEDED": 14,
  "IDLENESS_LIMIT_EXCEEDED": 1,
  "RUNTIME_ERROR": 13,
  "SKIPPED": 5
},
  topTags: [
  {
    "tag": "greedy",
    "count": 239
  },
  {
    "tag": "math",
    "count": 215
  },
  {
    "tag": "brute force",
    "count": 112
  },
  {
    "tag": "constructive algorithms",
    "count": 110
  },
  {
    "tag": "dp",
    "count": 100
  },
  {
    "tag": "implementation",
    "count": 95
  },
  {
    "tag": "sortings",
    "count": 85
  },
  {
    "tag": "data structures",
    "count": 73
  },
  {
    "tag": "binary search",
    "count": 73
  },
  {
    "tag": "number theory",
    "count": 61
  },
  {
    "tag": "two pointers",
    "count": 47
  },
  {
    "tag": "bitmasks",
    "count": 41
  }
],
} as const;

export const cfContests: CfContest[] = [
  {
    "date": "2024-05-26",
    "name": "Codeforces Round 948 (Div. 2)",
    "rank": 13450,
    "from": 0,
    "to": 374
  },
  {
    "date": "2025-02-09",
    "name": "Codeforces Round 1003 (Div. 4)",
    "rank": 13992,
    "from": 374,
    "to": 648
  },
  {
    "date": "2025-02-25",
    "name": "Codeforces Round 1006 (Div. 3)",
    "rank": 12758,
    "from": 648,
    "to": 850
  },
  {
    "date": "2025-02-27",
    "name": "Educational Codeforces Round 175 (Rated for Div. 2)",
    "rank": 13013,
    "from": 850,
    "to": 928
  },
  {
    "date": "2025-02-28",
    "name": "Codeforces Round 1007 (Div. 2)",
    "rank": 6463,
    "from": 928,
    "to": 1079
  },
  {
    "date": "2025-03-11",
    "name": "Codeforces Round 1009 (Div. 3)",
    "rank": 9156,
    "from": 1079,
    "to": 1126
  },
  {
    "date": "2025-03-29",
    "name": "Codeforces Round 1014 (Div. 2)",
    "rank": 9143,
    "from": 1126,
    "to": 1109
  },
  {
    "date": "2025-05-01",
    "name": "Codeforces Round 1022 (Div. 2)",
    "rank": 7699,
    "from": 1109,
    "to": 1073
  },
  {
    "date": "2025-05-11",
    "name": "Codeforces Round 1024 (Div. 2)",
    "rank": 7378,
    "from": 1073,
    "to": 1054
  },
  {
    "date": "2025-05-17",
    "name": "Codeforces Round 1025 (Div. 2)",
    "rank": 6665,
    "from": 1054,
    "to": 1098
  },
  {
    "date": "2025-06-12",
    "name": "Codeforces Round 1030 (Div. 2)",
    "rank": 3182,
    "from": 1098,
    "to": 1232
  },
  {
    "date": "2025-06-21",
    "name": "Codeforces Round 1033 (Div. 2) and CodeNite 2025",
    "rank": 7840,
    "from": 1232,
    "to": 1200
  },
  {
    "date": "2025-06-23",
    "name": "Educational Codeforces Round 180 (Rated for Div. 2)",
    "rank": 3856,
    "from": 1200,
    "to": 1271
  },
  {
    "date": "2025-07-01",
    "name": "Codeforces Round 1034 (Div. 3)",
    "rank": 807,
    "from": 1271,
    "to": 1405
  },
  {
    "date": "2025-07-05",
    "name": "Codeforces Round 1035 (Div. 2)",
    "rank": 3215,
    "from": 1405,
    "to": 1442
  },
  {
    "date": "2025-07-17",
    "name": "Codeforces Round 1037 (Div. 3)",
    "rank": 3103,
    "from": 1442,
    "to": 1441
  },
  {
    "date": "2025-08-10",
    "name": "Codeforces Round 1042 (Div. 3)",
    "rank": 6701,
    "from": 1441,
    "to": 1392
  },
  {
    "date": "2025-09-09",
    "name": "Codeforces Round 1049 (Div. 2)",
    "rank": 2561,
    "from": 1392,
    "to": 1448
  },
  {
    "date": "2025-10-24",
    "name": "Codeforces Round 1061 (Div. 2)",
    "rank": 1621,
    "from": 1448,
    "to": 1517
  },
  {
    "date": "2025-12-11",
    "name": "Codeforces Round 1070 (Div. 2)",
    "rank": 1513,
    "from": 1517,
    "to": 1565
  },
  {
    "date": "2025-12-19",
    "name": "Codeforces Global Round 31 (Div. 1 + Div. 2)",
    "rank": 3136,
    "from": 1565,
    "to": 1570
  },
  {
    "date": "2025-12-23",
    "name": "Codeforces Round 1071 (Div. 3)",
    "rank": 495,
    "from": 1570,
    "to": 1641
  }
];
